<html>
<head>
    <title><?php echo (isset($this->title) ? $this->title : 'KiwiJuicer'); ?></title>
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <!-- Optional theme -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">
    <!-- Latest compiled and minified JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
</head>
<body>
    <div id="nav">
        <ul class="nav nav-tabs nav-justified">
            <li class="dropdown">
                <a class="dropdown-toggle" data-toggle="dropdown" href="/" role="button" aria-haspopup="true" aria-expanded="false">
                    Home <span class="caret"></span>
                </a>
                <ul class="dropdown-menu">
                    Not Found <span class="glyphicon glyphicon-glas"></span>
                </ul>
            </li>
            <li>
                <a class="dropdown-toggle" data-toggle="dropdown" href="/notFound" role="button" aria-haspopup="true" aria-expanded="false">
                    Not Found <span class="glyphicon glyphicon-glas"></span>
                </a>
            </li>
        </ul>
    </div>
    <div class="container">
        <?php include $this->viewContentPath; ?>
    </div>
</body>
</html>