<div class="row">

    <div class="col-lg-12">

        <h1><?php echo $this->title; ?></h1>

        <table class="table table-hover">

            <tr>

                <th>Index</th>
                <th>Object</th>

            </tr>

            <?php foreach ($this->content as $index => $object) : ?>

                <tr>

                    <td><?php echo $index; ?></td>
                    <td><?php echo $object; ?></td>

                </tr>

            <?php endforeach; ?>

        </table>

    </div>

</div>